import { WebSocket } from "ws";

export interface IAuthPayload {
    username: string,
    expiresIn: number
}

export interface IConfPayload {
    conferenceId: number,
    conferenceRoomId: string,
    expiresIn: number,
    maxPeers: number
}


/**
 * active participant, the user has already authenticated
 */
export class Participant {
    participantId: string = ""; //generated by server to keep track of connections
    userName: string = ""; //username for the user, unique, used to login ie from a database
    displayName: string = ""; //display name for the user
    socket?: WebSocket = undefined; //websocket connection
    conferenceRoom?: ConferenceRoom = undefined; //reference to a conf room
}

export class ConferenceRoom {

    roomId: string;
    roomToken: string;

}