import { WebSocket } from "ws";

export interface IAuthPayload {
    username: string,
    expiresIn: number
}


/**
 * active participant, the user has already authenticated
 */
export class Participant {
    participantId: string = ""; //generated by server to keep track of connections
    userName: string = ""; //username for the user, unique, used to login ie from a database
    displayName: string = ""; //display name for the user
    socket?: WebSocket = undefined; //websocket connection
    conferenceRoom?: ConferenceRoom = undefined; //reference to a conf room
}

export class ConferenceRoom {
    id: string;
    roomURI: string;
    roomId: string;
    roomToken: string;
    participants: Map<string, Participant> = new Map();

    removeParticipant(id: string) {
        this.participants.delete(id);
    }

}