export interface User {
    id: string;
    displayName: string;
    role: "admin" | "user" | "guest";
}

export interface Conference {
    /**
     * tracking id is used to track the conference room
     * it is generated by the scheduling service
     */
    id: string;
    name: string;
    status: string;
    /**
     * conferenceRoomId is the id of the conference room that is live
     */
    conferenceRoomId?: string;
}

export interface Device {
    id: string;
    label: string;
}

export class CallParticipant {
    constructor(id: string, name: string) {
        this.id = id;
        this.displayName = name;
    }

    id: string = "";
    displayName: string = "";
    stream: MediaStream = new MediaStream();
    isMuted: boolean = false;
    isVideoOff: boolean = false;
}

